language: go

os: linux

if: (branch = master) OR (type = pull_request)

go: # use travis ci resource effectively, keep always latest 2 versions
  - 1.17.x
  - 1.16.x

install:
  - go get -v -t ./...

script:
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
